Add hover effect on sponsor image
reactbkk/2.0.0 pull request #141
Opened 2017-05-23 16:28 UTC by abzeede

![awesomescreenshot-2017-05-23t16-26-15-724z](https://cloud.githubusercontent.com/assets/9069649/26364742/879ba112-400f-11e7-9ad6-14cd5362f872.gif)

2017-05-23 16:32 UTC, dtinth requested changes
Thanks for your PRs. Here are some preliminary comments:

2017-05-23 16:32 UTC, dtinth commented on components/SponsorsSection.js
> +          cursor: pointer;
This does not make each sponsor a link. Please update your branch against latest `master` branch in this repository.

2017-05-23 16:32 UTC, dtinth commented on components/SponsorsSection.js
> +        .sponsor-item-gold:hover, .sponsor-item-silver:hover {
The scrolling effect should be applied to the clickable element, in this case, an `a` element.

Your pull request is based on an outdated code which does not contain the links. Please pull the latest master branch, and you should see a link.

2017-05-23 16:49 UTC, dtinth commented
The `:hover` should be placed on an `a` element because it is the interactive element.

2017-05-23 17:19 UTC, abzeede commented
@dtinth 
I've already fixed.

2017-05-23 17:23 UTC, dtinth requested changes
Few more changes requested. Please kindly check them out :)

2017-05-23 17:23 UTC, dtinth commented on components/SponsorsSection.js
> +        .sponsor-item-gold > a, .sponsor-item-silver > a{
You can just use `a` here because `styled-jsx` is scoped to the parent element. It will not affect other links on this page. Isn’t that cool? 😁

2017-05-23 17:23 UTC, dtinth commented on components/SponsorsSection.js
> +        .sponsor-item-gold > a:hover, .sponsor-item-silver > a:hover {
Here too, just `a:hover` is enough.

2017-05-23 17:33 UTC, abzeede commented on components/SponsorsSection.js
> +        .sponsor-item-gold > a:hover, .sponsor-item-silver > a:hover {
Oh! i see
thank you

2017-05-23 17:41 UTC, dtinth approved these changes

2017-05-24 07:19 UTC, merged

2017-05-24 12:05 UTC, abzeede commented
application #U3Z525W6